default: &default
  appid: "my_appid"
  appsecret: "my_secret"
  host:    "my_host"

development:
  <<: *default
  appsecret: "my_development_secret"
  host:    "my_development_host"

test:
  <<: *default
